/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cards.DeckOfCards;
//import sun.security.mscapi.CPublicKey;

import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.*;

/**
 *
 * @author Najafi
 */
public class OflflineMode extends javax.swing.JFrame {

    ArrayList<Integer> cards = new ArrayList<Integer>();
    JLabel[] playerLabel = new JLabel[5];
    JLabel[] dealerLabel = new JLabel[5];
    int numPlayer = 0;
    int numDealer = numPlayer + 1;
    int labeldealer = 0;
    int playerPoint = 0;
    int dealerPoint = 0;
    
    
    
    ImageIcon[] image = {
        new javax.swing.ImageIcon(getClass().getResource("/cards/del.6.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/del.7.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/del8.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/del.9.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/del.10.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/del.s.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/del.q.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/del.k.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/del.1.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.6.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.7.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.8.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.9.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.10.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.s.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.q.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.k.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/khesht.1.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.6.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.7.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.8.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.9.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.10.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.s.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.q.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.k.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/gisniz.1.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.6.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.7.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.8.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.9.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.10.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.s.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.q.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.k.png")),
        new javax.swing.ImageIcon(getClass().getResource("/cards/pik.1.png"))
    };

    /**
     * Creates new form OflflineMode
     */
    public OflflineMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hitBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        firstPic = new javax.swing.JLabel();
        secondBtn = new javax.swing.JLabel();
        thirdBtn = new javax.swing.JLabel();
        fourthBtn = new javax.swing.JLabel();
        fifthBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        dealerBtn1 = new javax.swing.JLabel();
        dealerBtn2 = new javax.swing.JLabel();
        dealerBtn3 = new javax.swing.JLabel();
        dealerBtn4 = new javax.swing.JLabel();
        dealerBtn5 = new javax.swing.JLabel();
        stayBtn = new javax.swing.JButton();
        restartBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        winOrLose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack | OfflineMode");
        setLocation(new java.awt.Point(350, 120));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hitBtn.setBackground(new java.awt.Color(221, 190, 169));
        hitBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        hitBtn.setForeground(new java.awt.Color(107, 112, 92));
        hitBtn.setText("HIT");
        hitBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        hitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 80, 40));

        jPanel2.setBackground(new java.awt.Color(183, 183, 164));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Table", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(107, 112, 92))); // NOI18N

        firstPic.setBackground(new java.awt.Color(204, 204, 255));
        firstPic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));
        firstPic.setMaximumSize(new java.awt.Dimension(60, 90));
        firstPic.setMinimumSize(new java.awt.Dimension(60, 90));

        secondBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        thirdBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        fourthBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        fifthBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(firstPic, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(secondBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(thirdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(fourthBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(fifthBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(thirdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fifthBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fourthBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPic, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 500, 130));

        jPanel3.setBackground(new java.awt.Color(183, 183, 164));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dealer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(107, 112, 92))); // NOI18N

        dealerBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        dealerBtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        dealerBtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        dealerBtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        dealerBtn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(dealerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(dealerBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(dealerBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(dealerBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(dealerBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dealerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 500, 130));

        stayBtn.setBackground(new java.awt.Color(221, 190, 169));
        stayBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        stayBtn.setForeground(new java.awt.Color(107, 112, 92));
        stayBtn.setText("stay");
        stayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(stayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 80, 40));

        restartBtn.setBackground(new java.awt.Color(221, 190, 169));
        restartBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        restartBtn.setForeground(new java.awt.Color(107, 112, 92));
        restartBtn.setText("Restart");
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(restartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        jPanel4.setBackground(new java.awt.Color(183, 183, 164));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92), new java.awt.Color(107, 112, 92)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 112, 92));
        jLabel2.setText("Details");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 106, 79));
        jLabel3.setText("Welcome,");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 106, 79));
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 106, 79));
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 106, 79));
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        winOrLose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        winOrLose.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(winOrLose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(winOrLose, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 200, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back/OfflineMode.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void hitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitBtnActionPerformed

        // firstPic.setIcon(image[0]);   add pic to jlabel:)
        restartBtn.setEnabled(false);
        
        jLabel5.setText("dealer point =0" );
        jLabel6.setText("last card point(dealer) =0" );

        for (int j = 1; j < 36; j++) {
            cards.add(j);
        }
        Collections.shuffle(cards);

        playerLabel[0] = firstPic;
        playerLabel[1] = secondBtn;
        playerLabel[2] = thirdBtn;
        playerLabel[3] = fourthBtn;
        playerLabel[4] = fifthBtn;

        playerPoint += DeckOfCards.value(cards.get(numPlayer));

        System.out.println(playerPoint);

        playerLabel[numPlayer].setIcon(image[cards.get(numPlayer) - 1]);
        playerLabel[numPlayer].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(183, 183, 164), new java.awt.Color(183, 183, 164), new java.awt.Color(183, 183, 164), new java.awt.Color(183, 183, 164)));

        jLabel3.setText("your point =" + playerPoint);
        jLabel4.setText("last card point(your) =" + Integer.toString(DeckOfCards.value(cards.get(numPlayer))));
        if (numPlayer < 5) {
            numPlayer++;
        }
        if (playerPoint>21) {
            winOrLose.setForeground(new java.awt.Color(208, 0, 0));
            winOrLose.setText("you Lose:(");
            hitBtn.setEnabled(false);
            stayBtn.setEnabled(false);
            restartBtn.setEnabled(true);
        }else if(playerPoint==21){
        winOrLose.setForeground(new java.awt.Color(128, 255, 219));
            winOrLose.setText("oh,you won:)");
            hitBtn.setEnabled(false);
            stayBtn.setEnabled(false);
            restartBtn.setEnabled(true);
        }

    }//GEN-LAST:event_hitBtnActionPerformed

    private void stayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stayBtnActionPerformed

            dealerLabel[0] = dealerBtn1;
            dealerLabel[1] = dealerBtn2;
            dealerLabel[2] = dealerBtn3;
            dealerLabel[3] = dealerBtn4;
            dealerLabel[4] = dealerBtn5;
        do {
            
            dealerPoint += DeckOfCards.value(cards.get(numDealer));

            System.out.println(dealerPoint);

            dealerLabel[labeldealer].setIcon(image[cards.get(numDealer) - 1]);
            dealerLabel[labeldealer].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(183, 183, 164), new java.awt.Color(183, 183, 164), new java.awt.Color(183, 183, 164), new java.awt.Color(183, 183, 164)));
            try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(OflflineMode.class.getName()).log(Level.SEVERE, null, ex);
                }
            jLabel5.setText("dealer point =" + dealerPoint);
            jLabel6.setText("last card point(dealer) =" + Integer.toString(DeckOfCards.value(cards.get(numDealer))));

            if (labeldealer < 5) {
                labeldealer++;
                numDealer++;
            }
                
        } while (playerPoint >= dealerPoint);
        
        
        if (dealerPoint > 21) {
            winOrLose.setForeground(new java.awt.Color(128, 255, 219));
            winOrLose.setText("you won:)");
            hitBtn.setEnabled(false);
            stayBtn.setEnabled(false);
            restartBtn.setEnabled(true);
        } else if (playerPoint <= dealerPoint) {
            winOrLose.setForeground(new java.awt.Color(208, 0, 0));
            winOrLose.setText("you Lose:(");
            hitBtn.setEnabled(false);
            stayBtn.setEnabled(false);
            restartBtn.setEnabled(true);
        } else {
            winOrLose.setForeground(new java.awt.Color(128, 255, 219));
            winOrLose.setText("you won:)");
            hitBtn.setEnabled(false);
            stayBtn.setEnabled(false);
            restartBtn.setEnabled(true);
        }

    }//GEN-LAST:event_stayBtnActionPerformed

    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
//        numPlayer = 0;
//        numDealer = numPlayer + 1;
//        labeldealer = 0;
//        playerPoint = 0;
//        dealerPoint = 0;
        OflflineMode o1=new OflflineMode();
        this.setVisible(false);
        o1.setVisible(true);
    }//GEN-LAST:event_restartBtnActionPerformed
    public static void dealerGame() {
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OflflineMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OflflineMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OflflineMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OflflineMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OflflineMode().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dealerBtn1;
    private javax.swing.JLabel dealerBtn2;
    private javax.swing.JLabel dealerBtn3;
    private javax.swing.JLabel dealerBtn4;
    private javax.swing.JLabel dealerBtn5;
    private javax.swing.JLabel fifthBtn;
    private javax.swing.JLabel firstPic;
    private javax.swing.JLabel fourthBtn;
    private javax.swing.JButton hitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton restartBtn;
    private javax.swing.JLabel secondBtn;
    private javax.swing.JButton stayBtn;
    private javax.swing.JLabel thirdBtn;
    private javax.swing.JLabel winOrLose;
    // End of variables declaration//GEN-END:variables
}
